### ISSUE TITLE
No callback when ETH received on generated address

### ISSUE THREAD

**Issue by PriyanshDwivedi** [coinbase/coinbase-php#155] opened 2018-02-01 14:33 UTC
Hi,

I generated an ETH address using modified coinbase-php library and assigned the callback url of my server to be called whenever funds are received.
Now, I made a test transaction to the generated ETH address and the transaction got confirmed, but there have been no callbacks to the callback url on coinbase console.
Has anyone ever got a successful callback on a generated ETH address from coinbase? Need help.

Address callbacks are working perfectly fine in case of BTC.

**Comment by PriyanshDwivedi** [comment] 2018-02-05 09:34
guys, any help? I even created a ticket on coinbase.com but no reply from their team. 
Losing business because of this issue :(

**Comment by Hackinet** [comment] 2018-02-13 19:11
Try doing to a test transaction again with this to check if you are getting anything at all.
```
<?php
$raw_body = file_get_contents('php://input');
$file = 'test.txt';
file_put_contents($file, $raw_body);
?>
```

**Comment by PriyanshDwivedi** [comment] 2018-02-13 19:47
The callback URL is not getting called. I have printed the input in log file but it is never called and there are no callbacks registered on coinbase console as well.

**Comment by Hackinet** [comment] 2018-02-16 17:22
I just tested it. The callback works. I got the notification after it was confirmed. I think there is a issue with your php code or you added the wrong url. Try sending demo test post data(You can use https://www.hurl.it ). Hope this helps.

**Comment by PriyanshDwivedi** [comment] 2018-02-16 18:06
The callback URL worked perfectly fine when tested from hurl.

Does the post data received in callback look like this?

`{"address":"0x846f4f811728714842E3c0c2FFB35159C3E0cE7C","amount":0.03,"transaction":{"id":"5a82762f2dea150001178bbd","created_at":"2018-02-12T21:22:55-08:00","hash":"0x4553e18883e9706846ee93a45b0a36ffc1adb8097cf19c6322b3c5025f65bca7","uuid":"05924466-0dcc-50b6-9c7e-8eb6cf04be22","resource_path":"/v2/accounts/31240543-0faf-52b9-94cb-795e2b5eb71a/transactions/05924466-0dcc-50b6-9c7e-8eb6cf04be22"},"uuid":"4cd12483-5065-578f-beac-f9d4f9d02a15","resource_path":"/v2/accounts/31240543-0faf-52b9-94cb-795e2b5eb71a/addresses/4cd12483-5065-578f-beac-f9d4f9d02a15"}`

**Comment by Hackinet** [comment] 2018-02-16 18:15
Follows this structure(Just _ETH_ in place of _BTC_):
```
{
  "id": "5a6956f9-94bb-5c15-99f3-a2a690347674",
  "type": "wallet:addresses:new-payment",
  "data": {
    "id": "c556eec7-53c2-576c-9158-c2eaa7c7ffca",
    "address": "mr4xYGzGMnw5tbbu2qyBBGdKwA4ktufbPy",
    "name": null,
    "created_at": "2015-01-31T20:49:02Z",
    "updated_at": "2015-01-31T20:49:02Z",
    "resource": "address",
    "resource_path": "/v2/accounts/c334783a-e72c-5e25-bf43-e182345f28c6/addresses/c556eec7-53c2-576c-9158-c2eaa7c7ffca"
  },
  "user": {
    "id": "5b5b60b6-2cd3-5f88-8539-3a78cd111b49",
    "resource": "user",
    "resource_path": "/v2/users/5b5b60b6-2cd3-5f88-8539-3a78cd111b49"
  },
  "account": {
    "id": "c334783a-e72c-5e25-bf43-e182345f28c6",
    "resource": "account",
    "resource_path": "/v2/accounts/c334783a-e72c-5e25-bf43-e182345f28c6"
  },
  "delivery_attempts": 0,
  "created_at": "2015-01-31T20:49:02Z",
  "resource": "notification",
  "resource_path": "/v2/notifications/5a6956f9-94bb-5c15-99f3-a2a690347674",
  "additional_data": {
    "hash": "749f267f9d238c978fe3e79a6c1f34070b0b8e5a3de8623d1bd144760bf79a5f",
    "amount": {
      "amount": "0.10000000",
      "currency": "BTC"
    },
    "transaction": {
      "id": "fe7b729d-62c6-5978-95ca-6cc1f9d23119",
      "resource": "transaction",
      "resource_path": "/v2/accounts/c334783a-e72c-5e25-bf43-e182345f28c6/transactions/fe7b729d-62c6-5978-95ca-6cc1f9d23119"
    }
  }
}
```

**Comment by PriyanshDwivedi** [comment] 2018-02-16 18:17
Thanks, will try and let you know. 
But this structure is totally different from what I saw in my account's BTC address callbacks.

**Comment by Hackinet** [comment] 2018-02-16 18:21
This structure is here: https://developers.coinbase.com/api/v2#metadata (http://prntscr.com/ifpopo)
I use this and it works for me. Should work for you too.

**Comment by PriyanshDwivedi** [comment] 2018-02-16 18:24
Sure, but atleast I should have seen an unsuccessful callback for that particular ETH address but it shows "no callbacks".

Will modify my callback according to this structure and test.

**Comment by PriyanshDwivedi** [comment] 2018-02-20 08:36
Modified my callback according to the structure and hit the exact callback url defined for the address from POSTMAN with structured test data and it worked fine, but still no callback registered when actual amount is received.

Also, why is the structure different in case of BTC callback. Below is the actual structure I receive for BTC address callbacks?

![screen shot 2018-02-20 at 2 02 01 pm](https://user-images.githubusercontent.com/18171669/36414105-1f162d88-1647-11e8-9d36-5db127a8e39c.png)

**Comment by sds** [comment] 2018-03-08 05:18
Hey @PriyanshDwivedi,

If I'm understanding correctly, this issue seems to be related to the API and is not an issue with the client library itself. For that reason I'm closing this issue.

In order to receive support for our API, please open a ticket with our [support team](https://support.coinbase.com/customer/en/portal/articles/2288496-how-can-i-contact-coinbase-support-). At the time you opened your ticket we had a large backlog, but we have [taken steps](https://blog.coinbase.com/customer-support-update-b91b9d8e6e46) to correct this. Thanks for your patience!

**Closed by sds** 2018-03-08 05:18 UTC
Labels: question
